name: Bug Report
description: Submit a tol
title: "[Tool]: "
labels: []
assignees:
  - kdheepak
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your tool for consideration!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Tool Name
      description: What is your software tool called
      placeholder: XYZ
    validations:
      required: true
  - type: input
    id: short-description
    attributes:
      label: Short Description
      description: Describe your tool in 140 characters or less
      placeholder: XYZ is a Energy System Model for ...
    validations:
      required: true
  - type: textarea
    id: long-description
    attributes:
      label: Long Description
      description: Describe your tool in as much detail as you'd like
      placeholder: ...
    validations:
      required: false
  - type: dropdown
    id: highest-temporal-resolution
    attributes:
      label: What is the highest resolution supported by the tool?
      multiple: false
      options:
        - Instant
        - Milliseconds
        - Seconds
        - Minutes
        - Hours
        - Days
        - Months
        - Years
        - Decades
    validations:
      required: true
  - type: dropdown
    id: lowest-temporal-resolution
    attributes:
      label: What is the lowest resolution supported by the tool?
      multiple: false
      options:
        - Instant
        - Milliseconds
        - Seconds
        - Minutes
        - Hours
        - Days
        - Months
        - Years
        - Decades
    validations:
      required: true
